#!/usr/bin/env zsh

# This function will add a file extention to all files in a directory.
# It will not replace files already with a file extention.
function remove-extension {

  echo -n "Continue?"
  read REPLY

  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    ext="$@"
    for file in *.$ext; do
        mv -- "$file" "${file%%.$ext}"
    done
  fi
}
